// SPDX-License-Identifier: GPL-3.0-or-later
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('tv', {
  init: () => ipcRenderer.invoke('yt:init'),
  signIn: () => ipcRenderer.invoke('yt:signIn'),
  signOut: () => ipcRenderer.invoke('yt:signOut'),
  isSignedIn: () => ipcRenderer.invoke('yt:isSignedIn'),
  listAccounts: () => ipcRenderer.invoke('yt:listAccounts'),
  addAccount: () => ipcRenderer.invoke('yt:addAccount'),
  selectAccount: (id) => ipcRenderer.invoke('yt:selectAccount', id),
  removeAccount: (id) => ipcRenderer.invoke('yt:removeAccount', id),
  setStartup: (mode) => ipcRenderer.invoke('yt:setStartup', mode),
  setDefaultAccount: (id) => ipcRenderer.invoke('yt:setDefaultAccount', id),
  startupInfo: () => ipcRenderer.invoke('yt:startupInfo'),
  setLocale: () => ipcRenderer.invoke('yt:setLocale'),
  netApply: () => ipcRenderer.invoke('net:apply'),
  rydGet: (id) => ipcRenderer.invoke('ryd:get', id),

  home: () => ipcRenderer.invoke('yt:home'),
  subscriptions: () => ipcRenderer.invoke('yt:subscriptions'),
  subscriptionChannels: () => ipcRenderer.invoke('yt:subChannels'),
  channelFeed: (params, name) => ipcRenderer.invoke('yt:channelFeed', params, name),
  channelPage: (id, name) => ipcRenderer.invoke('yt:channelPage', id, name),
  section: (name) => ipcRenderer.invoke('yt:section', name),
  playlists: (force) => ipcRenderer.invoke('yt:playlists', force),
  playlistFeed: (id, name) => ipcRenderer.invoke('yt:playlistFeed', id, name),
  music: () => ipcRenderer.invoke('yt:music'),
  addToPlaylist: (playlistId, videoId) => ipcRenderer.invoke('yt:addToPlaylist', playlistId, videoId),
  removeFromPlaylist: (playlistId, videoId) => ipcRenderer.invoke('yt:removeFromPlaylist', playlistId, videoId),
  removePlaylist: (playlistId) => ipcRenderer.invoke('yt:removePlaylist', playlistId),
  recordHistory: (id) => ipcRenderer.invoke('yt:recordHistory', id),
  removeFromHistory: (token) => ipcRenderer.invoke('yt:removeFromHistory', token),
  rate: (videoId, rating) => ipcRenderer.invoke('yt:rate', videoId, rating),
  setSubscribed: (channelId, subscribe) => ipcRenderer.invoke('yt:subscribe', channelId, subscribe),
  more: (section, view) => ipcRenderer.invoke('yt:more', section, view),
  moreShelf: (section, title) => ipcRenderer.invoke('yt:moreShelf', section, title),
  moreRelated: (videoId, exclude) => ipcRenderer.invoke('yt:moreRelated', videoId, exclude),
  relatedFresh: (videoId, exclude) => ipcRenderer.invoke('yt:relatedFresh', videoId, exclude),
  liveChatProbe: (id) => ipcRenderer.invoke('yt:liveChatProbe', id),
  liveChatStart: (id, filter) => ipcRenderer.invoke('yt:liveChatStart', id, filter),
  liveChatStop: () => ipcRenderer.invoke('yt:liveChatStop'),
  comments: (id, sort) => ipcRenderer.invoke('yt:comments', id, sort),
  moreComments: (id) => ipcRenderer.invoke('yt:moreComments', id),
  commentReplies: (id, commentId) => ipcRenderer.invoke('yt:commentReplies', id, commentId),
  search: (q) => ipcRenderer.invoke('yt:search', q),
  searchSuggest: (q) => ipcRenderer.invoke('yt:searchSuggest', q),
  searchHistory: () => ipcRenderer.invoke('search:historyGet'),
  searchHistoryAdd: (q) => ipcRenderer.invoke('search:historyAdd', q),
  searchHistoryClear: () => ipcRenderer.invoke('search:historyClear'),
  streams: (id) => ipcRenderer.invoke('yt:streams', id),
  sabr: (id, preferredLang, opts) => ipcRenderer.invoke('yt:sabr', id, preferredLang, opts),
  sabrReload: (id, reloadContext) => ipcRenderer.invoke('yt:sabrReload', id, reloadContext),
  sabrPoToken: (id) => ipcRenderer.invoke('yt:sabrPoToken', id),
  sponsorSegments: (id) => ipcRenderer.invoke('sb:segments', id),
  getSbSettings: () => ipcRenderer.invoke('sb:get'),
  setSbSettings: (patch) => ipcRenderer.invoke('sb:set', patch),
  dearrowBranding: (id) => ipcRenderer.invoke('dearrow:branding', id),
  getDearrowSettings: () => ipcRenderer.invoke('dearrow:get'),
  setDearrowSettings: (patch) => ipcRenderer.invoke('dearrow:set', patch),

  getUiSettings: () => ipcRenderer.invoke('ui:get'),
  setUiSettings: (patch) => ipcRenderer.invoke('ui:set', patch),

  authCopyCode: () => ipcRenderer.invoke('auth:copyCode'),
  authOpenUrl: () => ipcRenderer.invoke('auth:openUrl'),
  copyText: (t) => ipcRenderer.invoke('app:copyText', t),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  playbackEvent: (ev, vars) => ipcRenderer.invoke('app:playbackEvent', ev, vars),

  about: () => ipcRenderer.invoke('app:about'),
  checkUpdate: () => ipcRenderer.invoke('app:checkUpdate'),
  updateStatus: () => ipcRenderer.invoke('app:updateStatus'),
  downloadUpdate: () => ipcRenderer.invoke('app:downloadUpdate'),
  applyUpdateNow: () => ipcRenderer.invoke('app:applyUpdateNow'),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (_e, p) => cb(p)),

  logPath: () => ipcRenderer.invoke('app:logPath'),
  logError: (msg) => ipcRenderer.send('app:logError', msg),
  logInfo: (msg) => ipcRenderer.send('app:logInfo', msg),
  logDebug: (msg) => ipcRenderer.send('app:logDebug', msg),

  debugGet: () => ipcRenderer.invoke('debug:get'),
  debugSet: (on) => ipcRenderer.invoke('debug:set', on),
  debugExport: () => ipcRenderer.invoke('debug:export'),

  backupNow: () => ipcRenderer.invoke('backup:now'),
  onBackupProgress: (cb) => ipcRenderer.on('backup:progress', (_e, p) => cb(p)),
  backupList: () => ipcRenderer.invoke('backup:list'),
  backupRestore: (zipPath) => ipcRenderer.invoke('backup:restore', zipPath),
  backupBrowse: () => ipcRenderer.invoke('backup:browse'),
  backupGetCadence: () => ipcRenderer.invoke('backup:getCadence'),
  backupSetCadence: (v) => ipcRenderer.invoke('backup:setCadence', v),

  dlState: () => ipcRenderer.invoke('dl:state'),
  dlReady: () => ipcRenderer.invoke('dl:ready'),
  dlInstall: (which) => ipcRenderer.invoke('dl:install', which),
  dlUpdateYtdlp: () => ipcRenderer.invoke('dl:updateYtdlp'),
  dlCheckUpdates: () => ipcRenderer.invoke('dl:checkUpdates'),
  dlGetSettings: () => ipcRenderer.invoke('dl:getSettings'),
  dlSetSettings: (patch) => ipcRenderer.invoke('dl:setSettings', patch),
  dlChooseDir: () => ipcRenderer.invoke('dl:chooseDir'),
  onDlBinProgress: (cb) => ipcRenderer.on('dl:bin-progress', (_e, p) => cb(p)),
  onDlStateChange: (cb) => ipcRenderer.on('dl:state-change', (_e, st) => cb(st)),
  dlEnqueue: (info) => ipcRenderer.invoke('dl:enqueue', info),
  dlQueue: () => ipcRenderer.invoke('dl:queue'),
  dlCancel: (id) => ipcRenderer.invoke('dl:cancel', id),
  dlPause: (id) => ipcRenderer.invoke('dl:pause', id),
  dlResume: (id) => ipcRenderer.invoke('dl:resume', id),
  dlRemove: (id) => ipcRenderer.invoke('dl:remove', id),
  dlClearFinished: () => ipcRenderer.invoke('dl:clearFinished'),
  dlFormats: (videoId, url) => ipcRenderer.invoke('dl:formats', videoId, url),
  dlPrefetchFormats: (videoId, url) => ipcRenderer.invoke('dl:prefetchFormats', videoId, url),
  dlOpenFolder: () => ipcRenderer.invoke('dl:openFolder'),
  onDlQueueUpdate: (cb) => ipcRenderer.on('dl:queue-update', (_e, q) => cb(q)),
  onDlNotify: (cb) => ipcRenderer.on('dl:notify', (_e, n) => cb(n)),

  onAuthPending: (cb) => ipcRenderer.on('yt:auth-pending', (_e, data) => cb(data)),
  onAuthSuccess: (cb) => ipcRenderer.on('yt:auth-success', () => cb()),
  onAuthRestored: (cb) => ipcRenderer.on('yt:auth-restored', () => cb()),
  onFeedChunk: (cb) => ipcRenderer.on('yt:feed-chunk', (_e, data) => cb(data)),
  onFeedFresh: (cb) => ipcRenderer.on('yt:feed-fresh', (_e, data) => cb(data)),
  onLiveChat: (cb) => ipcRenderer.on('yt:live-chat', (_e, data) => cb(data)),

  quit: () => ipcRenderer.send('app:quit'),
  toggleFullscreen: () => ipcRenderer.send('app:toggleFullscreen'),

  // System preferences (run-in-tray + launch-on-startup); global, main-side.
  getSystemPrefs: () => ipcRenderer.invoke('system:get'),
  setSystemPrefs: (patch) => ipcRenderer.invoke('system:set', patch),

  // Companion remote (LAN WebSocket server): status, pairing, and device mgmt.
  companionStatus: () => ipcRenderer.invoke('companion:status'),
  companionStartPairing: () => ipcRenderer.invoke('companion:startPairing'),
  companionStopPairing: () => ipcRenderer.invoke('companion:stopPairing'),
  companionUnpair: (id) => ipcRenderer.invoke('companion:unpair', id),
  companionUnpairAll: () => ipcRenderer.invoke('companion:unpairAll'),
  onCompanionDevices: (cb) => ipcRenderer.on('companion:devices', (_e, d) => cb(d)),
  onCompanionCommand: (cb) => ipcRenderer.on('companion:command', (_e, m) => cb(m)),
  onCompanionPairRequested: (cb) => ipcRenderer.on('companion:pairRequested', (_e, info) => cb(info)),
  // State pushed TV -> phone (broadcast to authed devices). One-way sends;
  // onCompanionClients reports how many phones are connected so the renderer can
  // skip building payloads when nobody is listening.
  companionState: (s) => ipcRenderer.send('companion:state', s),
  companionQueue: (q) => ipcRenderer.send('companion:queue', q),
  companionPosition: (p) => ipcRenderer.send('companion:position', p),
  companionNotice: (m) => ipcRenderer.send('companion:notice', m),
  onCompanionClients: (cb) => ipcRenderer.on('companion:clients', (_e, n) => cb(n))
});
